version: v1
fields:
  - name: provider
    value: minikube
  - name: region
    configMapSource:
      ns: kube-system
      name: cluster-info
      field: cluster-region
  - name: workload-namespace
    workloadAttestorSource:
      name: workloadAttestor
      mapping:
      - type: k8s
        field: ns
  - name: workload-serviceAccount
    workloadAttestorSource:
      name: workloadAttestor
      mapping:
      - type: k8s
        field: sa
  - name: workload-podname
    workloadAttestorSource:
      name: workloadAttestor
      mapping:
      - type: k8s
        field: pod-name